# Base image
FROM node

# Base directory
WORKDIR /app

# Copy package.json in currect directory
COPY package.json .

# Install all dependencies
RUN npm install

# Copy all files
COPY . .

# Expose port
EXPOSE 3000

# Run project
CMD ["npm", "start"]