version: "3"
services:
    node-app:
        build:
            context: .
            args:
                NODE_ENV: development
        volumes:
            - ./:/app
            - /app/node_modules
        environment:
            - NODE_ENV=development
            - MONGO_USER=leoavilac
            - MONGO_PASSWORD=holamundo
            - SESSION_SECRET=holamundo
        command: npm run dev
        
    mongodb:
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=leoavilac
            - MONGO_INITDB_ROOT_PASSWORD=holamundo