version: "3.3"
services:
    react-app:
        build:
            context: ./react-app
            dockerfile: Dockerfile.dev
        links:
            - "node-app:na"

    nginx:
        image: nginx:stable-alpine
        ports:
            - "3001:81"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

    node-app:
        build: ./mongodb-redis-sopes1
        #ports:
        #    - "3001:3001"
        env_file:
            - ./mongodb-redis-sopes1/.env
        depends_on: 
            - mongodb

    # gRPC Client
    grpc-client:
        build: ./grpc-server/Client
        ports:
            - "80:3005"

    # gRPC Server
    grpc-server:
        build: ./grpc-server/Server

    # DB Server
    db-server:
        build: ./db-server
        environment:
            - MONGO_USER=leoavilac
            - MONGO_PASSWORD=holamundo

    # MongoDB Service
    mongodb:
        image: mongo
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=leoavilac
            - MONGO_INITDB_ROOT_PASSWORD=holamundo
        volumes:
            - mongo-db:/data/db

    # RedisDB Service
    redisdb:
        image: redis
        volumes:
            - redis-db:/data

# Persistent memory for DBs
volumes:
    mongo-db:
    redis-db: