version: "3"
services:
    react-app:
        build:
            context: ./react-app
            dockerfile: Dockerfile.prod
            args:
                - REACT_APP_NAME=leoavilac-prod
        ports:
            - "8080:80"
