version: "3"
services:
    react-app:
        build:
            context: ./react-app
            dockerfile: Dockerfile.dev
        links:
            - "node-app:na"
            
    node-app:
        build: ./mongodb-redis-sopes1
        ports:
            - "3001:3001"
        env_file:
            - ./mongodb-redis-sopes1/.env
        depends_on: 
            - mongodb

    mongodb:
        image: mongo
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=leoavilac
            - MONGO_INITDB_ROOT_PASSWORD=holamundo
        volumes:
            - mongo-db:/data/db

    redisdb:
        image: redis
        volumes:
            - redis-db:/data

volumes:
    mongo-db:
    redis-db: